### PR TITLE
Commit on Existing PRs

### LINKED ISSUE #12: Commit on exsisting PR
If the previous translation PR hasn't been merged shouldn't the bot commit to the existing PR instead of creating a new one? It would cut down on the spam when they're not being merged for a week or two.

Related comment: https://github.com/ScratchAddons/ScratchAddons/pull/7469#issuecomment-2131849119

### PR DESCRIPTION
**Pull request by Samq64**
Resolves #12

I tested the logic locally with the push and node lines commented out.

### CODE REVIEW

**Review by Hans5958 — APPROVED** [review]
We could try this.

**Comment by Hans5958** [comment]
If this works well enough, we can remove the date from the title.

**Comment by Samq64** [comment]
The date could be added to the commit messages instead.

**Comment by Hans5958** [comment]
Huh, it's failing.

https://github.com/ScratchAddons/ScratchAddons/actions/runs/12423492030/job/34687093816

Would you like to take a look?

**Comment by Samq64** [comment]
I forgot to run git fetch.

**Pull request merged**
