### PR TITLE
Use Transifex CLI to push and pull resource

### PR DESCRIPTION
**Pull request by apple502j**
Performance is bad so not merging now

### CODE REVIEW

**Comment by cobaltt7** [comment]
Why not use the python cli?

**Comment by apple502j** [comment]
@RedGuy12 Deprecated

**Comment by cobaltt7** [comment]
I'm talking about https://github.com/transifex/transifex-client

It's not deprecated yet, the replacement isn't even done yet

And I use it and it works fine

**Comment by apple502j** [comment]
The underlying API is deprecated and will be gone in 6 months.

**Pull request closed without merging**
